load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "parse-command",
    srcs = ["parse-command.cc"],
    hdrs =  ["include/parse-command.h"],
    copts = ["-Ilib/include"],
    visibility = ["//visibility:public"],
)
